Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pvlib

data, meta = pvlib.iotools.get_solrad(
    station='ABQ',  # station identifier
    start=pd.Timestamp(2020,6,1),
    end=pd.Timestamp(2020,6,5))

# show a subset of the data
show(data.iloc[:, 7:], dom="tpr")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mIncompleteRead[0m                            Traceback (most recent call last)
File [0;32m/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/response.py:748[0m, in [0;36mHTTPResponse._error_catcher[0;34m(self)[0m
[1;32m    747[0m [38;5;28;01mtry[39;00m:
[0;32m--> 748[0m     [38;5;28;01myield[39;00m
[1;32m    750[0m [38;5;28;01mexcept[39;00m SocketTimeout [38;5;28;01mas[39;00m e:
[1;32m    751[0m     [38;5;66;03m# FIXME: Ideally we'd like to include the url in the ReadTimeoutError but[39;00m
[1;32m    752[0m     [38;5;66;03m# there is yet no clean way to get at it from this context.[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/response.py:894[0m, in [0;36mHTTPResponse._raw_read[0;34m(self, amt, read1)[0m
[1;32m    884[0m     [38;5;28;01mif[39;00m (
[1;32m    885[0m         [38;5;28mself[39m[38;5;241m.[39menforce_content_length
[1;32m    886[0m         [38;5;129;01mand[39;00m [38;5;28mself[39m[38;5;241m.[39mlength_remaining [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[0;32m   (...)[0m
[1;32m    892[0m         [38;5;66;03m# raised during streaming, so all calls with incorrect[39;00m
[1;32m    893[0m         [38;5;66;03m# Content-Length are caught.[39;00m
[0;32m--> 894[0m         [38;5;28;01mraise[39;00m IncompleteRead([38;5;28mself[39m[38;5;241m.[39m_fp_bytes_read, [38;5;28mself[39m[38;5;241m.[39mlength_remaining)
[1;32m    895[0m [38;5;28;01melif[39;00m read1 [38;5;129;01mand[39;00m (
[1;32m    896[0m     (amt [38;5;241m!=[39m [38;5;241m0[39m [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m data) [38;5;129;01mor[39;00m [38;5;28mself[39m[38;5;241m.[39mlength_remaining [38;5;241m==[39m [38;5;28mlen[39m(data)
[1;32m    897[0m ):
[0;32m   (...)[0m
[1;32m    900[0m     [38;5;66;03m# `http.client.HTTPResponse`, so we close it here.[39;00m
[1;32m    901[0m     [38;5;66;03m# See https://github.com/python/cpython/issues/113199[39;00m

[0;31mIncompleteRead[0m: IncompleteRead(65536 bytes read, 115959 more expected)

The above exception was the direct cause of the following exception:

[0;31mProtocolError[0m                             Traceback (most recent call last)
File [0;32m/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/models.py:820[0m, in [0;36mResponse.iter_content.<locals>.generate[0;34m()[0m
[1;32m    819[0m [38;5;28;01mtry[39;00m:
[0;32m--> 820[0m     [38;5;28;01myield from[39;00m [38;5;28mself[39m[38;5;241m.[39mraw[38;5;241m.[39mstream(chunk_size, decode_content[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m    821[0m [38;5;28;01mexcept[39;00m ProtocolError [38;5;28;01mas[39;00m e:

File [0;32m/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/response.py:1060[0m, in [0;36mHTTPResponse.stream[0;34m(self, amt, decode_content)[0m
[1;32m   1059[0m [38;5;28;01mwhile[39;00m [38;5;129;01mnot[39;00m is_fp_closed([38;5;28mself[39m[38;5;241m.[39m_fp) [38;5;129;01mor[39;00m [38;5;28mlen[39m([38;5;28mself[39m[38;5;241m.[39m_decoded_buffer) [38;5;241m>[39m [38;5;241m0[39m:
[0;32m-> 1060[0m     data [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m[43mamt[49m[38;5;241;43m=[39;49m[43mamt[49m[43m,[49m[43m [49m[43mdecode_content[49m[38;5;241;43m=[39;49m[43mdecode_content[49m[43m)[49m
[1;32m   1062[0m     [38;5;28;01mif[39;00m data:

File [0;32m/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/response.py:977[0m, in [0;36mHTTPResponse.read[0;34m(self, amt, decode_content, cache_content)[0m
[1;32m    973[0m [38;5;28;01mwhile[39;00m [38;5;28mlen[39m([38;5;28mself[39m[38;5;241m.[39m_decoded_buffer) [38;5;241m<[39m amt [38;5;129;01mand[39;00m data:
[1;32m    974[0m     [38;5;66;03m# TODO make sure to initially read enough data to get past the headers[39;00m
[1;32m    975[0m     [38;5;66;03m# For example, the GZ file header takes 10 bytes, we don't want to read[39;00m
[1;32m    976[0m     [38;5;66;03m# it one byte at a time[39;00m
[0;32m--> 977[0m     data [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_raw_read[49m[43m([49m[43mamt[49m[43m)[49m
[1;32m    978[0m     decoded_data [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_decode(data, decode_content, flush_decoder)

File [0;32m/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/response.py:872[0m, in [0;36mHTTPResponse._raw_read[0;34m(self, amt, read1)[0m
[1;32m    870[0m fp_closed [38;5;241m=[39m [38;5;28mgetattr[39m([38;5;28mself[39m[38;5;241m.[39m_fp, [38;5;124m"[39m[38;5;124mclosed[39m[38;5;124m"[39m, [38;5;28;01mFalse[39;00m)
[0;32m--> 872[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39m_error_catcher():
[1;32m    873[0m     data [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_fp_read(amt, read1[38;5;241m=[39mread1) [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m fp_closed [38;5;28;01melse[39;00m [38;5;124mb[39m[38;5;124m"[39m[38;5;124m"[39m

File [0;32m/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/contextlib.py:158[0m, in [0;36m_GeneratorContextManager.__exit__[0;34m(self, typ, value, traceback)[0m
[1;32m    157[0m [38;5;28;01mtry[39;00m:
[0;32m--> 158[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mgen[49m[38;5;241;43m.[39;49m[43mthrow[49m[43m([49m[43mvalue[49m[43m)[49m
[1;32m    159[0m [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m [38;5;28;01mas[39;00m exc:
[1;32m    160[0m     [38;5;66;03m# Suppress StopIteration *unless* it's the same exception that[39;00m
[1;32m    161[0m     [38;5;66;03m# was passed to throw().  This prevents a StopIteration[39;00m
[1;32m    162[0m     [38;5;66;03m# raised inside the "with" statement from being suppressed.[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/response.py:772[0m, in [0;36mHTTPResponse._error_catcher[0;34m(self)[0m
[1;32m    771[0m         arg [38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;124mConnection broken: [39m[38;5;132;01m{[39;00me[38;5;132;01m!r}[39;00m[38;5;124m"[39m
[0;32m--> 772[0m     [38;5;28;01mraise[39;00m ProtocolError(arg, e) [38;5;28;01mfrom[39;00m [38;5;21;01me[39;00m
[1;32m    774[0m [38;5;28;01mexcept[39;00m (HTTPException, [38;5;167;01mOSError[39;00m) [38;5;28;01mas[39;00m e:

[0;31mProtocolError[0m: ('Connection broken: IncompleteRead(65536 bytes read, 115959 more expected)', IncompleteRead(65536 bytes read, 115959 more expected))

During handling of the above exception, another exception occurred:

[0;31mChunkedEncodingError[0m                      Traceback (most recent call last)
Cell [0;32mIn[3], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpvlib[39;00m
[0;32m----> 3[0m data, meta [38;5;241m=[39m [43mpvlib[49m[38;5;241;43m.[39;49m[43miotools[49m[38;5;241;43m.[39;49m[43mget_solrad[49m[43m([49m
[1;32m      4[0m [43m    [49m[43mstation[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mABQ[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m  [49m[38;5;66;43;03m# station identifier[39;49;00m
[1;32m      5[0m [43m    [49m[43mstart[49m[38;5;241;43m=[39;49m[43mpd[49m[38;5;241;43m.[39;49m[43mTimestamp[49m[43m([49m[38;5;241;43m2020[39;49m[43m,[49m[38;5;241;43m6[39;49m[43m,[49m[38;5;241;43m1[39;49m[43m)[49m[43m,[49m
[1;32m      6[0m [43m    [49m[43mend[49m[38;5;241;43m=[39;49m[43mpd[49m[38;5;241;43m.[39;49m[43mTimestamp[49m[43m([49m[38;5;241;43m2020[39;49m[43m,[49m[38;5;241;43m6[39;49m[43m,[49m[38;5;241;43m5[39;49m[43m)[49m[43m)[49m
[1;32m      8[0m [38;5;66;03m# show a subset of the data[39;00m
[1;32m      9[0m show(data[38;5;241m.[39miloc[:, [38;5;241m7[39m:], dom[38;5;241m=[39m[38;5;124m"[39m[38;5;124mtpr[39m[38;5;124m"[39m)

File [0;32m/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pvlib/iotools/solrad.py:208[0m, in [0;36mget_solrad[0;34m(station, start, end, url)[0m
[1;32m    206[0m [38;5;28;01mfor[39;00m f [38;5;129;01min[39;00m filenames:
[1;32m    207[0m     [38;5;28;01mtry[39;00m:
[0;32m--> 208[0m         dfi, file_metadata [38;5;241m=[39m [43mread_solrad[49m[43m([49m[43murl[49m[43m [49m[38;5;241;43m+[39;49m[43m [49m[43mf[49m[43m)[49m
[1;32m    209[0m         dfs[38;5;241m.[39mappend(dfi)
[1;32m    210[0m     [38;5;28;01mexcept[39;00m requests[38;5;241m.[39mexceptions[38;5;241m.[39mHTTPError:

File [0;32m/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pvlib/iotools/solrad.py:111[0m, in [0;36mread_solrad[0;34m(filename)[0m
[1;32m    108[0m meta [38;5;241m=[39m {}
[1;32m    110[0m [38;5;28;01mif[39;00m [38;5;28mstr[39m(filename)[38;5;241m.[39mstartswith([38;5;124m'[39m[38;5;124mftp[39m[38;5;124m'[39m) [38;5;129;01mor[39;00m [38;5;28mstr[39m(filename)[38;5;241m.[39mstartswith([38;5;124m'[39m[38;5;124mhttp[39m[38;5;124m'[39m):
[0;32m--> 111[0m     response [38;5;241m=[39m [43mrequests[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[43mfilename[49m[43m)[49m
[1;32m    112[0m     response[38;5;241m.[39mraise_for_status()
[1;32m    113[0m     file_buffer [38;5;241m=[39m io[38;5;241m.[39mStringIO(response[38;5;241m.[39mcontent[38;5;241m.[39mdecode())

File [0;32m/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/api.py:73[0m, in [0;36mget[0;34m(url, params, **kwargs)[0m
[1;32m     62[0m [38;5;28;01mdef[39;00m [38;5;21mget[39m(url, params[38;5;241m=[39m[38;5;28;01mNone[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m     63[0m [38;5;250m    [39m[38;5;124mr[39m[38;5;124;03m"""Sends a GET request.[39;00m
[1;32m     64[0m 
[1;32m     65[0m [38;5;124;03m    :param url: URL for the new :class:`Request` object.[39;00m
[0;32m   (...)[0m
[1;32m     70[0m [38;5;124;03m    :rtype: requests.Response[39;00m
[1;32m     71[0m [38;5;124;03m    """[39;00m
[0;32m---> 73[0m     [38;5;28;01mreturn[39;00m [43mrequest[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mget[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43murl[49m[43m,[49m[43m [49m[43mparams[49m[38;5;241;43m=[39;49m[43mparams[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/api.py:59[0m, in [0;36mrequest[0;34m(method, url, **kwargs)[0m
[1;32m     55[0m [38;5;66;03m# By using the 'with' statement we are sure the session is closed, thus we[39;00m
[1;32m     56[0m [38;5;66;03m# avoid leaving sockets open which can trigger a ResourceWarning in some[39;00m
[1;32m     57[0m [38;5;66;03m# cases, and look like a memory leak in others.[39;00m
[1;32m     58[0m [38;5;28;01mwith[39;00m sessions[38;5;241m.[39mSession() [38;5;28;01mas[39;00m session:
[0;32m---> 59[0m     [38;5;28;01mreturn[39;00m [43msession[49m[38;5;241;43m.[39;49m[43mrequest[49m[43m([49m[43mmethod[49m[38;5;241;43m=[39;49m[43mmethod[49m[43m,[49m[43m [49m[43murl[49m[38;5;241;43m=[39;49m[43murl[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/sessions.py:589[0m, in [0;36mSession.request[0;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)[0m
[1;32m    584[0m send_kwargs [38;5;241m=[39m {
[1;32m    585[0m     [38;5;124m"[39m[38;5;124mtimeout[39m[38;5;124m"[39m: timeout,
[1;32m    586[0m     [38;5;124m"[39m[38;5;124mallow_redirects[39m[38;5;124m"[39m: allow_redirects,
[1;32m    587[0m }
[1;32m    588[0m send_kwargs[38;5;241m.[39mupdate(settings)
[0;32m--> 589[0m resp [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43msend[49m[43m([49m[43mprep[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43msend_kwargs[49m[43m)[49m
[1;32m    591[0m [38;5;28;01mreturn[39;00m resp

File [0;32m/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/sessions.py:746[0m, in [0;36mSession.send[0;34m(self, request, **kwargs)[0m
[1;32m    743[0m         [38;5;28;01mpass[39;00m
[1;32m    745[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m stream:
[0;32m--> 746[0m     [43mr[49m[38;5;241;43m.[39;49m[43mcontent[49m
[1;32m    748[0m [38;5;28;01mreturn[39;00m r

File [0;32m/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/models.py:902[0m, in [0;36mResponse.content[0;34m(self)[0m
[1;32m    900[0m         [38;5;28mself[39m[38;5;241m.[39m_content [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m    901[0m     [38;5;28;01melse[39;00m:
[0;32m--> 902[0m         [38;5;28mself[39m[38;5;241m.[39m_content [38;5;241m=[39m [38;5;124;43mb[39;49m[38;5;124;43m"[39;49m[38;5;124;43m"[39;49m[38;5;241;43m.[39;49m[43mjoin[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43miter_content[49m[43m([49m[43mCONTENT_CHUNK_SIZE[49m[43m)[49m[43m)[49m [38;5;129;01mor[39;00m [38;5;124mb[39m[38;5;124m"[39m[38;5;124m"[39m
[1;32m    904[0m [38;5;28mself[39m[38;5;241m.[39m_content_consumed [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m    905[0m [38;5;66;03m# don't need to release the connection; that's been handled by urllib3[39;00m
[1;32m    906[0m [38;5;66;03m# since we exhausted the data.[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/models.py:822[0m, in [0;36mResponse.iter_content.<locals>.generate[0;34m()[0m
[1;32m    820[0m     [38;5;28;01myield from[39;00m [38;5;28mself[39m[38;5;241m.[39mraw[38;5;241m.[39mstream(chunk_size, decode_content[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m    821[0m [38;5;28;01mexcept[39;00m ProtocolError [38;5;28;01mas[39;00m e:
[0;32m--> 822[0m     [38;5;28;01mraise[39;00m ChunkedEncodingError(e)
[1;32m    823[0m [38;5;28;01mexcept[39;00m DecodeError [38;5;28;01mas[39;00m e:
[1;32m    824[0m     [38;5;28;01mraise[39;00m ContentDecodingError(e)

[0;31mChunkedEncodingError[0m: ('Connection broken: IncompleteRead(65536 bytes read, 115959 more expected)', IncompleteRead(65536 bytes read, 115959 more expected))

